[project]
name = "mathstralpix"
version = "0.1.0"
description = "Smol script for OCR'ing mathematics"
requires-python = ">=3.8"
dependencies = [
    "pillow",
    "mistralai",
    "python-dotenv",
    "kivy"
]

[tool.ruff]
select = ["E", "F", "I"]
ignore = []
line-length = 88 
